### ISSUE TITLE
Keep alive signal

### ISSUE THREAD

**Issue by Gnindit** [austinsc/node-red-contrib-envisalink-dsc#3]
Does this code send a keep alive signal?

From the manual
Poll
The TPI will respond with a Command Acknowledge code.
Note: The POLL command will also reset the Envisalink's network watchdog
timer. If there is no communications with the Envisalerts servers for a
period of 20 minutes, the Envisallink will reboot. Sending the TPI POLL
command will reset this timer. Useful if the module is not connected to the
Internet or firewalled.

**Comment by austinsc** [comment]
Sounds like it does- this probably has more to do with the online service envisalink provides but it could be leveraged by a custom flow in node red if you don't want it to have internet access.
